dat = 'man_cont_loads'
NDIM =  80, IPS =   4, IRS =   0, ILP =   0
ICP =  [4,20,21,27,15,16,17,18,13,14,22,23,24,25]
NTST =  50, NCOL=   4, IAD =   3, ISP =   2, ISW = 1, IPLT= 0, NBC= 92, NINT= 1
NMX =   200000, NPR= 0, MXBF=  10, IID =   2, ITMX= 8, ITNW= 7, NWTN= 3, JAC= 0
EPSL =  1e-08, EPSU = 1e-08, EPSS =1e-6
DS  = -1e-2, DSMIN=  1e-4, DSMAX=  1e-1, IADS=   1
NPAR = 36, THL =  {11: 0.0}, THU =  {}
